"""
main.py
FINNEX AI+ backend entry point.

Run locally:
    uvicorn main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

import uuid

from fastapi import FastAPI, Depends, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware

import database as db
import auth
import finance_engine as fe
import ai_chat
import notifications
import receipt_scanner
import transaction_import
from models import (
    SignupRequest, LoginRequest, TokenResponse, TransactionIn, TransactionUpdate, BudgetIn,
    GoalIn, GoalDepositIn, BillIn, ChatRequest, RiskProfileIn, AccountIn, CurrencyIn,
)
import currency as currency_module

app = FastAPI(title="FINNEX AI+ API", version="1.0.0")

# In production, replace "*" with your actual frontend domain(s).
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

db.init_db()


@app.get("/")
def root():
    return {"status": "ok", "service": "FINNEX AI+ API"}


# ============================================================
# AUTH
# ============================================================

@app.post("/auth/signup", response_model=TokenResponse)
def signup(payload: SignupRequest):
    if db.get_user_by_email(payload.email):
        raise HTTPException(status_code=400, detail="An account with this email already exists.")
    pw_hash, salt = auth.hash_password(payload.password)
    user_id = db.create_user(payload.email, payload.name, pw_hash, salt)
    token = auth.create_token(user_id, payload.email)
    return {"access_token": token, "user": {"id": user_id, "name": payload.name, "email": payload.email}}


@app.post("/auth/login", response_model=TokenResponse)
def login(payload: LoginRequest):
    user = db.get_user_by_email(payload.email)
    if not user or not auth.verify_password(payload.password, user["password_hash"], user["salt"]):
        raise HTTPException(status_code=401, detail="Invalid email or password.")
    token = auth.create_token(user["id"], user["email"])
    return {"access_token": token, "user": {"id": user["id"], "name": user["name"], "email": user["email"]}}


@app.put("/auth/risk-profile")
def update_risk_profile(payload: RiskProfileIn, user_id: int = Depends(auth.get_current_user_id)):
    db.set_risk_profile(user_id, payload.risk_profile)
    return {"success": True}


# ============================================================
# CURRENCY (country-based currency preference + live exchange rate)
# ============================================================

@app.get("/currency/countries")
def list_countries():
    """Returns the country -> currency options for the selector UI. No auth
    required since it's static reference data."""
    return [
        {"country": country, "currency": code, "symbol": symbol}
        for country, (code, symbol) in currency_module.COUNTRY_CURRENCIES.items()
    ]


@app.get("/currency/rate")
def get_currency_rate(user_id: int = Depends(auth.get_current_user_id)):
    """Returns the logged-in user's preferred currency, its symbol, and the
    current USD exchange rate (live if reachable, otherwise a documented
    fallback). All amounts are stored in USD; conversion is display-only."""
    user = db.get_user_by_id(user_id)
    target = user.get("currency", "USD")
    rate_info = currency_module.get_exchange_rate(target)
    rate_info["symbol"] = currency_module.symbol_for(target)
    return rate_info


@app.put("/auth/currency")
def update_currency(payload: CurrencyIn, user_id: int = Depends(auth.get_current_user_id)):
    db.set_currency(user_id, payload.currency.upper())
    return {"success": True}


# ============================================================
# TRANSACTIONS (Income & Expense Management)
# ============================================================

@app.post("/transactions")
def create_transaction(payload: TransactionIn, user_id: int = Depends(auth.get_current_user_id)):
    category = payload.category or fe.categorize(payload.description, payload.merchant, payload.type)
    tx_id = db.add_transaction(
        user_id, payload.date, payload.type, category, payload.merchant,
        payload.description, payload.amount, int(payload.is_recurring), payload.account_id,
    )
    return {"id": tx_id, "category": category}


@app.get("/transactions")
def list_transactions(user_id: int = Depends(auth.get_current_user_id)):
    return db.get_transactions(user_id)


@app.put("/transactions/{tx_id}")
def edit_transaction(tx_id: int, payload: TransactionUpdate, user_id: int = Depends(auth.get_current_user_id)):
    db.update_transaction(user_id, tx_id, **payload.dict(exclude_unset=True))
    return {"success": True}


@app.delete("/transactions/{tx_id}")
def remove_transaction(tx_id: int, user_id: int = Depends(auth.get_current_user_id)):
    db.delete_transaction(user_id, tx_id)
    return {"success": True}


# ---- Import your own file (CSV) --------------------------------------
# Upload once with POST /transactions/import, then every row it added is
# tagged with one shared batch id. GET the history to show past imports,
# and DELETE a batch id to undo that whole import in one go without
# touching anything else (manual entries or other imports).

@app.post("/transactions/import")
async def import_transactions(
    file: UploadFile = File(...),
    account_id: int = None,
    user_id: int = Depends(auth.get_current_user_id),
):
    raw = await file.read()
    if not raw:
        raise HTTPException(status_code=400, detail="The uploaded file is empty.")

    try:
        rows, parse_errors = transaction_import.parse_transactions_csv(raw)
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))

    if not rows:
        raise HTTPException(
            status_code=422,
            detail="No valid rows could be imported. " + " ".join(parse_errors[:5]),
        )

    batch_id = uuid.uuid4().hex
    for row in rows:
        db.add_transaction(
            user_id, row["date"], row["type"], row["category"], row["merchant"],
            row["description"], row["amount"], row["is_recurring"], account_id,
            import_batch_id=batch_id, import_filename=file.filename,
        )

    return {
        "batch_id": batch_id,
        "filename": file.filename,
        "imported": len(rows),
        "skipped": len(parse_errors),
        "errors": parse_errors[:20],  # cap so a bad file doesn't flood the response
    }


@app.get("/transactions/import/history")
def import_history(user_id: int = Depends(auth.get_current_user_id)):
    return db.get_import_batches(user_id)


@app.delete("/transactions/import/{batch_id}")
def undo_import(batch_id: str, user_id: int = Depends(auth.get_current_user_id)):
    removed = db.delete_import_batch(user_id, batch_id)
    if removed == 0:
        raise HTTPException(status_code=404, detail="Import batch not found.")
    return {"success": True, "removed": removed}


# ============================================================
# ACCOUNTS (Bank & Wallet Management)
# ============================================================

@app.post("/accounts")
def create_account(payload: AccountIn, user_id: int = Depends(auth.get_current_user_id)):
    acc_id = db.add_account(user_id, payload.name, payload.type, payload.initial_balance)
    return {"id": acc_id}


@app.get("/accounts")
def list_accounts(user_id: int = Depends(auth.get_current_user_id)):
    return db.get_account_balances(user_id)


@app.delete("/accounts/{account_id}")
def remove_account(account_id: int, user_id: int = Depends(auth.get_current_user_id)):
    db.delete_account(user_id, account_id)
    return {"success": True}


# ============================================================
# BUDGETS
# ============================================================

@app.post("/budgets")
def upsert_budget(payload: BudgetIn, user_id: int = Depends(auth.get_current_user_id)):
    db.set_budget(user_id, payload.category, payload.monthly_limit)
    return {"success": True}


@app.get("/budgets")
def list_budgets(user_id: int = Depends(auth.get_current_user_id)):
    return db.get_budgets(user_id)


# ============================================================
# GOALS
# ============================================================

@app.post("/goals")
def create_goal(payload: GoalIn, user_id: int = Depends(auth.get_current_user_id)):
    goal_id = db.add_goal(user_id, payload.name, payload.target_amount, payload.target_date)
    return {"id": goal_id}


@app.get("/goals")
def list_goals(user_id: int = Depends(auth.get_current_user_id)):
    return db.get_goals(user_id)


@app.post("/goals/{goal_id}/deposit")
def deposit_to_goal(goal_id: int, payload: GoalDepositIn, user_id: int = Depends(auth.get_current_user_id)):
    db.update_goal_savings(user_id, goal_id, payload.amount)
    return {"success": True}


# ============================================================
# BILLS / EMI REMINDERS
# ============================================================

@app.post("/bills")
def create_bill(payload: BillIn, user_id: int = Depends(auth.get_current_user_id)):
    bill_id = db.add_bill(user_id, payload.name, payload.amount, payload.due_date, payload.recurring)
    return {"id": bill_id}


@app.get("/bills")
def list_bills(user_id: int = Depends(auth.get_current_user_id)):
    return db.get_bills(user_id)


@app.put("/bills/{bill_id}/pay")
def pay_bill(bill_id: int, user_id: int = Depends(auth.get_current_user_id)):
    db.mark_bill_paid(user_id, bill_id)
    return {"success": True}


@app.get("/bills/reminders")
def bill_reminders(within_days: int = 7, user_id: int = Depends(auth.get_current_user_id)):
    """Returns unpaid bills due within `within_days` days — used to power the
    dashboard 'due soon' banner. For real push/email reminders, call this
    endpoint from a scheduled job (cron / APScheduler) and send a
    notification for each bill returned."""
    return db.get_due_soon_bills(user_id, within_days)


@app.post("/bills/reminders/send-emails")
def trigger_bill_reminder_emails(within_days: int = 3):
    """
    Sends email reminders to every user with bills due soon. Requires
    SMTP_HOST / SMTP_USER / SMTP_PASSWORD to be set (see .env.example).
    Intended to be called by an external cron job once a day, e.g.:
        curl -X POST https://your-api.com/bills/reminders/send-emails
    Not user-scoped since it's meant for a scheduler, not the logged-in user.
    """
    return notifications.send_due_bill_emails(within_days)


# ============================================================
# AI INSIGHTS: health score, prediction, subscriptions, investment
# ============================================================

@app.get("/insights/health-score")
def health_score(user_id: int = Depends(auth.get_current_user_id)):
    tx = db.get_transactions(user_id)
    budgets = db.get_budgets(user_id)
    goals = db.get_goals(user_id)
    return fe.financial_health_score(tx, budgets, goals)


@app.get("/insights/prediction")
def spending_prediction(user_id: int = Depends(auth.get_current_user_id)):
    tx = db.get_transactions(user_id)
    return fe.predict_month_end_expense(tx)


@app.get("/insights/subscriptions")
def subscriptions(user_id: int = Depends(auth.get_current_user_id)):
    tx = db.get_transactions(user_id)
    return fe.detect_subscriptions(tx)


@app.get("/insights/savings-suggestions")
def savings_suggestions(user_id: int = Depends(auth.get_current_user_id)):
    """Concrete, actionable ways to reduce spending, based on the user's
    actual budgets, subscriptions, and category totals this month."""
    tx = db.get_transactions(user_id)
    budgets = db.get_budgets(user_id)
    return fe.expense_reduction_suggestions(tx, budgets)


@app.get("/insights/investment")
def investment_plan(user_id: int = Depends(auth.get_current_user_id)):
    user = db.get_user_by_id(user_id)
    tx = db.get_transactions(user_id)
    totals = fe.monthly_totals(tx)
    if totals:
        latest = list(totals.values())[-1]
        surplus = max(0, latest["income"] - latest["expense"])
    else:
        surplus = 0
    return fe.investment_allocation(user["risk_profile"], surplus)


@app.get("/insights/dashboard")
def dashboard_summary(user_id: int = Depends(auth.get_current_user_id)):
    """One-shot endpoint the frontend dashboard calls to minimize round trips."""
    tx = db.get_transactions(user_id)
    budgets = db.get_budgets(user_id)
    goals = db.get_goals(user_id)
    bills = db.get_bills(user_id)
    accounts = db.get_account_balances(user_id)
    return {
        "monthly_totals": fe.monthly_totals(tx),
        "health_score": fe.financial_health_score(tx, budgets, goals),
        "prediction": fe.predict_month_end_expense(tx),
        "subscriptions": fe.detect_subscriptions(tx),
        "budgets": budgets,
        "goals": goals,
        "upcoming_bills": [b for b in bills if not b["paid"]],
        "due_soon_bills": db.get_due_soon_bills(user_id, 7),
        "accounts": accounts,
        "total_balance": round(sum(a["balance"] for a in accounts), 2),
        "recent_transactions": tx[:10],
    }


# ============================================================
# AI CHATBOT
# ============================================================

@app.post("/chat")
def chat(payload: ChatRequest, user_id: int = Depends(auth.get_current_user_id)):
    tx = db.get_transactions(user_id)
    budgets = db.get_budgets(user_id)
    goals = db.get_goals(user_id)
    bills = db.get_bills(user_id)
    answer = ai_chat.ask(payload.message, tx, budgets, goals, bills)
    return {"answer": answer}


# ============================================================
# RECEIPT SCANNER (AI vision -- Gemini/OpenAI, with a local
# Tesseract fallback for anyone who has that installed)
# ============================================================

@app.post("/receipts/scan")
async def scan_receipt(file: UploadFile = File(...), user_id: int = Depends(auth.get_current_user_id)):
    image_bytes = await file.read()
    mime_type = file.content_type or "image/jpeg"
    result = receipt_scanner.parse_receipt(image_bytes, mime_type)
    if not result["success"]:
        raise HTTPException(status_code=422, detail=result["error"])
    return result
